### PR TITLE
Adding drag and drop of mails using the SortableJs library

### PR DESCRIPTION
**Pull request by NasserNgandu**
### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by NasserNgandu** [comment]
Here is the link of the task: https://avan.tech/item44205-Cypht-Add-drag-and-drop.

**Comment by dumblob** [comment]
Thanks for taking stab at this!

Before anyone will dive into to the source I wonder whether ~3.7k SLOC library is worth including?

Are there other **real** (not just hypothetical, not "for future") benefits of the (quite huge I'd say) JS library for Cypht?

**Comment by marclaporte** [comment]
Related feature request: https://github.com/jasonmunro/cypht/issues/216

**Comment by marclaporte** [comment]
https://github.com/SortableJS/Sortable/blob/master/Sortable.js is bigger than https://github.com/bevacqua/dragula/blob/master/dist/dragula.js

Last commit in 2020-09  (15 months is not a disqualifier but a concern)
https://github.com/bevacqua/dragula/commits/master


Another topic: should we use minified version?
https://github.com/SortableJS/Sortable/blob/master/Sortable.min.js

**Comment by marclaporte** [comment]
@dumblob There is more analysis at https://github.com/jasonmunro/cypht/issues/216

I feel the decision is "good enough" and not worth investing more time. But if you or someone come with a better option, we can look into swapping.

Thanks!

**Comment by dumblob** [comment]
@marclaporte I see - thanks for the analysis of "liveness" of the biggest contenders.

On the other hand I'd still prefer evaluating the following 3 criteria (in this order) in addition to project liveness:

1. the user feel on a smartphone/tablet of the given library (yes, touch support is different and some implementations really feel very weird & unintuitive and some do feel much better)
2. the simplicity and "smartness" of the API (i.e. how much it'll influence Cypht future design & decisions, how easy is it to learn, how orthogonal to other Cypht JS code it is, etc.)
3. whether it dictates anything peculiar about the underlying html structure or not (if it does, then it goes the "React" route of constrained bulky widgets which is something Cypht IMHO doesn't want to go)

On the other hand, if the library you want to choose **now** will not influence Cypht design and APIs and thus will be easily exchangeable, then I'd take the first such library which also suits your devs as that's what counts the most at the beginning. We can later see if we could optimize (do better) in the sense of point (1) above or at least in the sense of the library size.

**Comment by marclaporte** [comment]
With the currently proposed integration, 4 lines of code are modified. So the lib is easily interchangeable later. I do expect us to add drag and drop in a few other places like folder management but I don't expect it to influence Cypht.

I tested https://sortablejs.github.io/Sortable/ in touch mode, and it works well. Only issue I noticed in the "Handle" mode: the handle is small and not easy to catch.

SortableJS has MultiDrag, which makes a lot of sense for email:
https://github.com/SortableJS/Sortable/wiki/Dragging-Multiple-Items-in-Sortable

**Comment by jasonmunro** [comment]
I'm a bit confused by this PR - What exactly is the point of this? To re-order the list on the client side? The order is not sticky (and will most likely break new message arrival placement in the list) so I really don't understand the use case. @marclaporte can you help me out here?

**Comment by marclaporte** [comment]
This is the goal: https://github.com/jasonmunro/cypht/issues/216


So pick 3 messages and drag and drop to a folder.

**Comment by NasserNgandu** [comment]
I'm sorry, I misunderstood the task. The code just changes the order of the emails. I'll fix that ASAP.

**Comment by jasonmunro** [comment]
> I'm sorry, I misunderstood the task. The code just changes the order of the emails. I'll fix that ASAP.

I think this is going to be _maybe_ a bit tricky. Let me know if you get stuck on anything I'm happy to help!

**Pull request closed without merging**
