### PR TITLE
Sieve: added more options to block/ban page

### PR DESCRIPTION
**Pull request by josaphatim**
This merge request adds more options to block/ban page

It helps users to know who is blocked offering the possibility to block
- The whole domain
- Specific email

Also it helps choose the action to be executed
- Default action: This is specified in the block_list page where users choose the default action (Discard/Reject with a default message)
- Discard
- Move to Banned folder
- Reject with default message
- Reject with specific message

Relates: https://avan.tech/item92586

### CODE REVIEW

**Comment by marclaporte** [comment]
Will require this: https://github.com/henrique-borba/php-sieve-manager/pull/2

**Comment by marclaporte** [comment]
About terminology: We are using many terms, like
* Banned
* Block
* Reject
* Bounce
* Discard
* ....
And some of these are synonyms in our context.


I think in the code and visible to end users, we should avoid synonyms and converge on a terminology.

We should stick to upstream standard, unless there is a reason to diverge. Ex.: It's not good/clear.

So let's make the list of synonyms, and after, we can pick the best one.
* Block, ban
* Reject, bounce
* Discard, delete, remove
* Any others?

**Comment by kroky** [comment]
Looks good to me. @josaphatim are you still working on something here?

**Comment by josaphatim** [comment]
> Looks good to me. @josaphatim are you still working on something here?

I just need to change terminology as @marclaporte suggested.

**Comment by josaphatim** [comment]
> About terminology: We are using many terms, like
> 
> * Banned
> * Block
> * Reject
> * Bounce
> * Discard
> * ....
>   And some of these are synonyms in our context.
> 
> I think in the code and visible to end users, we should avoid synonyms and converge on a terminology.
> 
> We should stick to upstream standard, unless there is a reason to diverge. Ex.: It's not good/clear.
> 
> So let's make the list of synonyms, and after, we can pick the best one.
> 
> * Block, ban
> * Reject, bounce
> * Discard, delete, remove
> * Any others?

@marclaporte I think now everything is okay

**Comment by marclaporte** [comment]
Terminology looks good to me.

**Pull request merged**
