### PR TITLE
Cypht admin panel: Indicate if default value or not (like Tiki)

### PR DESCRIPTION
**Pull request by NasserNgandu**
### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by NasserNgandu** [comment]
Here is the link of the task: https://avan.tech/item35517-Cypht-admin-panel-Indicate-if-default-value-or-not-like-Tiki.

**Comment by jasonmunro** [comment]
settings

This is a cool feature and I'm happy to merge this, but I have one small request: Can we force the reset icon to be on the same line as the setting instead of occasionally appearing on a new line below the setting? Thanks!

**Comment by NasserNgandu** [comment]
Ok thank you I put the icon on the same line.

**Comment by jasonmunro** [comment]
> Ok thank you I put the icon on the same line.

I don't see any updates on this, I will merge once it is added to the PR, thanks!

**Comment by NasserNgandu** [comment]
It is done. Thanks !

**Comment by NasserNgandu** [comment]
It is done. Thanks !

**Comment by jasonmunro** [comment]
Looks good thanks for the work!

**Pull request merged**
