### PR TITLE
Fix sent folder issue

### PR DESCRIPTION
**Pull request by eric-ampire**
## Pullrequest

Filter folder page to show sent mails properly when it's custom sent folder

### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] None

### Todo

- [X] None

### CODE REVIEW

**Comment by kk6mrp** [comment]
I tried this earlier today and it didn't fix the issue like in https://github.com/jasonmunro/cypht/issues/433

**Comment by jasonmunro** [comment]
Looks good I will merge and do some testing. Thanks!

**Comment by marclaporte** [comment]
@kk6mrp Maybe this? https://github.com/jasonmunro/cypht/pull/509

**Comment by kk6mrp** [comment]
No I think I misunderstood his intent.

**Pull request merged**
