### PR TITLE
Added an error message when the attachments folder does not exist or when there is a permussion problem.

### PR DESCRIPTION
**Pull request by NasserNgandu**

### CODE REVIEW

**Comment by NasserNgandu** [comment]
When the attachments folder is not present or when there is a permission problem. An error message is displayed to the user, and the add attachments button is disabled. For Cypht standalone and Cypht in Tiki.
error_attachment

**Comment by jasonmunro** [comment]
This looks good but could you change the message to:

"Attachment storage unavailable, please contact your site administrator"

Thanks!

**Comment by NasserNgandu** [comment]
Thanks, it's done !

**Comment by jasonmunro** [comment]
Thanks!

**Comment by NasserNgandu** [comment]
Thanks !

**Pull request merged**
