### PR TITLE
Fix unremovable text preferences/settings

### PR DESCRIPTION
**Pull request by josaphatim**
## Pullrequest
Updated code to support emptying settings with string values.

### Issues
- relates https://avan.tech/item81566

### CODE REVIEW

**Comment by jasonmunro** [comment]
Sorry, I merge this thinking it looked innocent but it is breaking unit tests. I honestly don't know exactly what this change was supposed to fix but I think we need to find another solution. Happy to help if you can explain what the specific issue is!

**Comment by marclaporte** [comment]
It's possible to edit values, but not remove (empty) them completely. When you try, they just come back. Seen on "Gmail Client ID"

**Comment by jasonmunro** [comment]
Thanks for the clarification, pushed a fix to master

**Comment by marclaporte** [comment]
Sorry for breaking the tests. I added https://github.com/jasonmunro/cypht/issues/596

**Pull request merged**
