### PR TITLE
Allow addition of non-sieve IMAP account

### PR DESCRIPTION
**Pull request by josaphatim**
## Pullrequest
Non sieve IMAP account are not added in all cases (when sieve filters is checked or not). This merge request fixes that

### Issues
- relates https://avan.tech/item82261

### CODE REVIEW

**Comment by marclaporte** [comment]
This didn't work for me. @jasonmunro You can ignore this one for now.

**Comment by josaphatim** [comment]
> This didn't work for me. @jasonmunro You can ignore this one for now.

I have corrected. Think it is now okay.

**Comment by marclaporte** [comment]
I confirm it worked for me.

**Comment by jasonmunro** [comment]
thanks for the fix on this!

**Pull request merged**
