### PR TITLE
Fix reply to issue

### PR DESCRIPTION
**Pull request by Revisto**
Hello, I am Revisto from WikiSuite project.
I did this [Cypht: When we reply to an email we have sent, it proposes our address](https://avan.tech/item60589-Cypht-When-we-reply-to-an-email-we-have-sent-it-proposes-our-address) which was related to this [issue](https://github.com/jasonmunro/cypht/issues/384). I handled the situation when replying to myself, it shows the other person's email in the 'message to' section.

### CODE REVIEW

**Comment by marclaporte** [comment]
There are commits related to your factory reset enhancement.

**Comment by Revisto** [comment]
> There are commits related to your factory reset enhancement.

Yes, I made a mistake, I made a branch from the factory reset branch. I will fix it.

**Comment by jasonmunro** [comment]
Not sure this is a good idea, and even if so, I'm pretty sure this change has unintended consequences. If I am replying to a message, even one sent from one of my own addresses, it should pick the sender of the message from the available header fields. Why would I want it to populate the To: address when I selected reply? Also this change prioritizes return-path in all cases which I am pretty sure is not what we want.

**Comment by marclaporte** [comment]
@Revisto Please research and report on how other webmails do it, especially Gmail and Roundcube.

Thanks!

**Comment by marclaporte** [comment]
Fixed here: https://github.com/jasonmunro/cypht/pull/530

**Pull request closed without merging**
