### PR TITLE
Add warning went send message with sent folder undefined

### PR DESCRIPTION
**Pull request by yvesdaxmaz**
## Pullrequest

Made update to alert user when he try to send a message without defining a SENT FOLDER where sent messages should be saved.

### Issues

- [X] None

### Checklist

- [X] None

### How2Test

- [X] Compose a new message without defining sent folder 
- [X] There should be a warning alert which show "Unable to send message: Please configure your folder to save sent messages (Sent Folder)"
### Todo

- [X] None

### CODE REVIEW

**Comment by marclaporte** [comment]
What about when I delete a message, does it go to trash? If trash folder is not defined, then what?

**Comment by marclaporte** [comment]
I lost a message again today because I forgot to set the sent on a new mail account.

**Comment by jasonmunro** [comment]
@marclaporte deleting a message with no trash setup while similar, should have it's own PR. @yvesdaxmaz I can't merge this as is because it will make it impossible to send a message without a configured sent folder. I agree the user should be aware of the missing sent folder, but it should not be impossible to send without it.

**Comment by marclaporte** [comment]
@adrienmaloba: Since Yves is unavailable nowadays, please take over.

Thanks!

**Comment by henrique-borba** [comment]
> @marclaporte deleting a message with no trash setup while similar, should have it's own PR. @yvesdaxmaz I can't merge this as is because it will make it impossible to send a message without a configured sent folder. I agree the user should be aware of the missing sent folder, but it should not be impossible to send without it.

In this case @adrienmaloba @marclaporte,  if we just need to warn the user maybe we can just replace 
`Hm_Msgs::add("Message Sent");` (Line 507) with:

```PHP
 $specials = $this->user_config->get('special_imap_folders', array());
        if(array_key_exists($smtp_id, $specials) || empty($specials)){
            if(!array_key_exists('sent', $specials[$smtp_id]) || empty($specials[$smtp_id]['sent'])) {
                Hm_Msgs::add('Message Sent.');
                Hm_Msgs::add('ERRPlease configure your folder to save sent messages (Sent Folder)');
         }
 }
```

It is simple and won't require JS or ajax calls, but you will lose your first email.

**Comment by dumblob** [comment]
> It is simple and won't require JS or ajax calls, but you will lose your first email.

Oh no, please. I've lost already several emails during the past few years due to MUAs doing such mistakes. It's of the highest priority to not lose any information the user has created or received.

**Comment by henrique-borba** [comment]
> > It is simple and won't require JS or ajax calls, but you will lose your first email.
> 
> Oh no, please. I've lost already several emails during the past few years due to MUAs doing such mistakes. It's of the highest priority to not lose any information the user has created or received.

I just chatted with @adrienmaloba and he is actually pretty advanced on the solution to check it before the email is sent so don't mind my last comment 👍

**Comment by henrique-borba** [comment]
Fixed in https://github.com/jasonmunro/cypht/pull/493

**Pull request closed without merging**
