### PR TITLE
[FIX] Cypht webmail view on a folder in mobile mode: Should have a search box

### PR DESCRIPTION
**Pull request by jeanpaulHamuli**
## Pullrequest

Cypht webmail view on a folder in mobile mode: Should have a search box 

### Issues

https://avan.tech/item54308-Cypht-webmail-view-on-a-folder-in-mobile-mode-Should-have-a-search-box

### Checklist

- [X] None

### How2Test

- [ ] Go to Email->All
- [ ] In the search box write something then click Enter

### Todo

- [X] None

### CODE REVIEW

**Comment by jasonmunro** [comment]
The problem here is the search box overlaps on top of the message list title. Depending on the width of the mobile device it can completely cover it. I specifically removed search (and sort) from mobile because of this reason. If we want to add this back we need to figure out a better layout, either a second row in the heading area or a search icon that makes the input box visible. We should fix the sort dialog as well as it has the same issue since be re-enabled on mobile.

**Comment by marclaporte** [comment]
ok, let's go for an improved layout as search is so critical.

**Comment by jeanpaulHamuli** [comment]
Understand, let's improve it

**Comment by jeanpaulHamuli** [comment]
This is what I suggest, adding a second row was not good. How do you find the @jasonmunro idea?
cyphtImg

**Comment by jasonmunro** [comment]
Looks great, thanks for reworking this!

**Pull request merged**
