### PR TITLE
Fix mobile look for sieve filter

### PR DESCRIPTION
**Pull request by ElvisAns**
### Issues

- The sieve filter page was not looking good on mobile devices

### Checklist

- To make sure the new styles are applied run the config_gen.php file (eg . `php ./scripts/config_gen.php`)

### How2Test

- Pull this branch, apply the config gen then navigate where you add filters/scripts  for your emails
- Make sure you have configured sieve filters when adding the mail 

### Todo

- Other things related to the whole web app look and feel eg. the login page...

### CODE REVIEW

**Comment by jasonmunro** [comment]
This looks good. One thing I noticed was the @screen css based on width 600px. It's fine, however keep in mind we do a server side check for mobile devices and add a class to the body tag called "mobile" when on a mobile. This can be used to apply your style to any mobile devices. Example: https://github.com/jasonmunro/cypht/blob/master/modules/core/site.css#L208

**Comment by ElvisAns** [comment]
I used media queries for applying styles for mobiles devices especially, so instead i am supposed to use only the .mobile class and the server side will add the class whenever the user is browsing from mobile device?

**Comment by jasonmunro** [comment]
> I used media queries for applying styles for mobiles devices especially, so instead i am supposed to use only the .mobile class and the server side will add the class whenever the user is browsing from mobile device?

That is exactly correct :)

**Comment by ElvisAns** [comment]
@jasonmunro  i hope now it is looking good

**Comment by jasonmunro** [comment]
:+1: thanks for updating this

**Pull request merged**
